- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Resolve #19 by following the https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc
> Enable the Release Drafter based on jenkinsci documentation

- Jenkinsfile
- build.gradle
- script/check-plugin-verification.sh
- src/main/resources/META-INF/plugin.xml
Verify against the last three years of the releases.
Also, `CI` env variable is set so that `gradle-intellij-plugin` can skip steps that it thinks are not necessary for CI, e.g. downloading sources.
> Adopt the IntelliJ Plugin Verifier into the Build and CI

- src/main/resources/META-INF/plugin.xml
This should enable plugin transfer as per [Plugin transfer](https://plugins.jetbrains.com/docs/marketplace/organizations.html#plugin-transfer) doc.  Which then enable more contributors to upload new version.
> Change the plugin vendor from KK to jenkins organization

- src/main/java/org/kohsuke/stapler/idea/JellyFileTypeFactory.java
- src/main/java/org/kohsuke/stapler/idea/jelly/JellyFileType.java
Fix #58 by registering Jelly file type
Instead of adding an extension to an XML file type which appears to be not working on 2021.2 a new FileType is added which still maps to the XML language.
- ~[ ] Link to relevant pull requests, esp. upstream and downstream changes~
> Restore the association bet *.jelly and XML language

- build.gradle
- src/test/java/org/kohsuke/stapler/idea/JexlInspectionTest.java
- src/test/testData/parserFailureJexlInspection.jelly
Use the commons-logging provided by the platform to avoid class initialization exception due to LogFactory inside the commons-jexl
Fixes #51
- ~[ ] Link to relevant pull requests, esp. upstream and downstream changes~
A test is added but it works just fine even without a fix. The classpath in the test must be different from the runtime making the problem not reproducible.
> JEXL Inspection crashes are fixed by addressing logger initialization issue in JEXL

- src/main/java/org/kohsuke/stapler/idea/JellyDocumentationProvider.java
- src/main/resources/META-INF/plugin.xml
* Refactor by using `AbstractDocumentationProvider` the abstract class suggested in the [docs](https://plugins.jetbrains.com/docs/intellij/documentation.html#implementation) instead of the interface `DocumentationProvider`
* Exit when the nullable parameter is `null`. At the moment, the decision on what doc to show is based purely on this argument so nothing to do when it is empty.
> Avoid #78 by short-circuiting on null in nullable parameter. 

- src/main/java/io/jenkins/stapler/idea/jelly/JellyFileTypeSchema.java
- src/main/java/org/kohsuke/stapler/idea/JellyAnnotator.java
- src/main/java/org/kohsuke/stapler/idea/JellyCompletionContributor.java
- src/main/java/org/kohsuke/stapler/idea/JellyDocumentationProvider.java
- src/main/java/org/kohsuke/stapler/idea/JellyLanguageInjector.java
- src/main/java/org/kohsuke/stapler/idea/JexlInspection.java
- src/main/java/org/kohsuke/stapler/idea/descriptor/AnyElementDescriptorImpl.java
- src/main/java/org/kohsuke/stapler/idea/descriptor/JellyTaglibMetadataContributor.java
- src/main/java/org/kohsuke/stapler/idea/descriptor/StaplerCustomJellyTagLibraryXmlNSDescriptor.java
- src/main/java/org/kohsuke/stapler/idea/descriptor/StaplerCustomJellyTagLibraryXmlSchemaProvider.java
- src/main/java/org/kohsuke/stapler/idea/descriptor/StaplerCustomJellyTagfileXmlAttributeDescriptor.java
- src/main/java/org/kohsuke/stapler/idea/descriptor/StaplerCustomJellyTagfileXmlElementDescriptor.java
- src/main/java/org/kohsuke/stapler/idea/descriptor/XmlElementDescriptorProviderImpl.java
- src/main/java/org/kohsuke/stapler/idea/dom/model/AttributeTag.java
- src/main/resources/META-INF/plugin.xml
While investigating the StackOverflowError-s I noticed that XML metadata contributed by the plugins is specific for the [CustomTagLibrary](https://github.com/jenkinsci/stapler/blob/1709.ve4c10835694b_/jelly/src/main/java/org/kohsuke/stapler/jelly/CustomTagLibrary.java) feature of Stapler. I decided to:
* Rename the classes appropriately to better align with stapler's codebase and hopefully improve readability
* Add the "jellytag" to the supported Jelly file extensions since it is expected by at least two tag library implementations: CustomTagLibrary and ThisTagLibrary. (It is barely used in real life, though).
> `jellytag` extension is now supported since Stapler supports it for Tag Libraries. 

- build.gradle
- gradle.properties
- src/main/java/org/kohsuke/stapler/idea/JellyLanguageInjector.java
Fixes #103 
Issue reproduced:
- use IDEA ultimate edition, which contains the CSS plugin (only for ultimate)
1. open any jelly file, and start typing:
<div style=
2. here, two double-quotes are added, CSS language is injected and auto-completion works between double-quotes
<div style=""
3. now, start typing an additional = next to to the previous =
<div style==""
=> error occurs
Changes:
- updated IDE versions (2022.2.3) in `build.gradle`
- added `type` attribute in `build.gradle` in order to be able to use ultimate edition during tests
- checked condition of `value.getTextLength()`
To test:
- `runIde -PideaVersion=<some version> -PideaType=IU` -> will run ultimate edition which contains CSS plugin
- reproduce steps, and see no exception, and completion works when syntax correctly fomed
> Fix "IllegalArgumentException: Invalid range specified: (1, -1)" when editing `style` attribute in Jelly files

- src/main/resources/fileTemplates/Jenkins Jelly view.jelly.ft
- src/main/resources/fileTemplates/config.jelly.ft
I have followed the tutorials here https://plugins.jetbrains.com/docs/intellij/providing-file-templates.html to start making file templates. This is for issue here -  https://github.com/jenkinsci/idea-stapler-plugin/issues/41
> A file template is added for a Stapler Jelly View

- build.gradle
- gradle.properties
- src/main/java/org/kohsuke/stapler/idea/icons/Icons.java
Fixes #100 
Configuration of `runPluginVerifier` with list generated from `listProductsReleases` with `sinceVersion`.
Example of output when running `gradle runPluginVerifier -PideaVersion=2022.2.3` :
```
> Task :listProductsReleases
IC-2022.3
IC-2022.2.3
IC-2022.1.4
IC-2021.3.3
IC-2021.2.4
IC-2021.1.3
IC-2020.3.4
```
```
> Task :verifyPlugin
Download https://cache-redirector.jetbrains.com/download.jetbrains.com/idea/ideaIC-2021.3.3.tar.gz (32.73 MB / 802.97 MB)> Task :runPluginVerifier
Download https://cache-redirector.jetbrains.com/download.jetbrains.com/idea/ideaIC-2021.3.3.tar.gz, took 5 m 46 s 838 ms (802.97 MB)
Download https://cache-redirector.jetbrains.com/download.jetbrains.com/idea/ideaIC-2021.2.4.tar.gz, took 4 m 14 s 968 ms (839.65 MB)
Download …
```
> Avoid hardcoding releases to verify agains, by using JetBrains Gradle plugin feature that lists the releases

- src/main/java/io/jenkins/stapler/idea/jelly/JellyFileTypeSchema.java
- src/main/java/org/kohsuke/stapler/idea/JellyAnnotator.java
- src/main/java/org/kohsuke/stapler/idea/JellyCompletionContributor.java
- src/main/java/org/kohsuke/stapler/idea/JellyLanguageInjector.java
- src/main/java/org/kohsuke/stapler/idea/JexlInspection.java
- src/main/java/org/kohsuke/stapler/idea/descriptor/StaplerCustomJellyTagLibraryXmlNSDescriptor.java
- src/main/java/org/kohsuke/stapler/idea/descriptor/StaplerCustomJellyTagLibraryXmlSchemaProvider.java
As discussed with @jgreffe . After his introduction of Jelly Language and file type, things could be simplified.
* `JellyFileTypeSchema` is left but the only public API now are constants that define Jelly extensions
* Where no longer necessary checks that the current file is Jelly are removed
* Where still necessary, instead of extension, a type of file object is checked instead.
> Leverage new JellyFile type in more of the codebase

- build.gradle
Reverts jenkinsci/idea-stapler-plugin#124
On Intel macOS 13.0.1 with 2020.3 as and IDEA version target the `buildPlugin` and `runIde` stopped working. They fork a process that prints a warning about `UseConcMarkSweepGC` and then `ClassNotFoundException` and exits with 1.
Reverting until baseline is updated.
> Revert "Bump org.jetbrains.intellij from 1.9.0 to 1.10.0"

- .editorconfig
- .github/workflows/gradle-dependency-submission.yml
https://github.blog/changelog/2023-02-08-dependency-submission-suggestions-on-gradle-maven-scala-and-mill-repositories/
> Gradle Dependency Submission action is enabled

- src/main/java/org/kohsuke/stapler/idea/JexlInspection.java
- src/test/java/org/kohsuke/stapler/idea/JexlInspectionTest.java
- src/test/testData/i18nLookups.jelly
- src/test/testData/smokeJexlInspection.jelly
Fixes #126 
- handle case of non-closed quotes
- unescape content before parsing
> i18n with single-quote exception Argument rangeInElement (9,25) endOffset must not exceed descriptor text range (38, 62) length (24)

- src/main/resources/org/kohsuke/stapler/idea/resources/schemas/stapler.xsd
The tag does already exist, see https://github.com/jenkinsci/stapler/blob/cea4497990e88143e543410ea0817c15b3e86d1a/jelly/src/main/java/org/kohsuke/stapler/jelly/AttributeTag.java#L75-L79, yet remained undocumented.
This PR takes care of that.
> Add 'since' attribute to the 'attribute' tag of the Stapler tag library

- src/main/resources/org/kohsuke/stapler/idea/resources/schemas/ant.xsd
- src/main/resources/org/kohsuke/stapler/idea/resources/schemas/core.xsd
- src/main/resources/org/kohsuke/stapler/idea/resources/schemas/define.xsd
- src/main/resources/org/kohsuke/stapler/idea/resources/schemas/dynabean.xsd
- src/main/resources/org/kohsuke/stapler/idea/resources/schemas/fmt.xsd
- src/main/resources/org/kohsuke/stapler/idea/resources/schemas/junit.xsd
- src/main/resources/org/kohsuke/stapler/idea/resources/schemas/log.xsd
- src/main/resources/org/kohsuke/stapler/idea/resources/schemas/stapler.xsd
- src/main/resources/org/kohsuke/stapler/idea/resources/schemas/util.xsd
- src/main/resources/org/kohsuke/stapler/idea/resources/schemas/xml.xsd
These updates have been generated by running `mvn clean org.jvnet.maven-jellydoc-plugin:maven-jellydoc-plugin:1.11:jellydoc` in the jelly and stapler repository. The output aligns with the format we're using there and the binaries produced.
To note, there are more XSDs available in the https://github.com/jenkinsci/jelly/tree/master/jelly-tags folder, but we don't build or distribute these, and they are not maven-ized. Therefore, I didn't include XSD updates for them.
Closes #145 
Fixes #92
> Update Jelly Tag Library XSDs

- src/main/java/org/kohsuke/stapler/idea/extension/JavaStructureViewExtension.java
> Add support for groovy views as well as help files in the structure view

- Jenkinsfile
This PR removes the `clean` gradle task not needed on ci.jenkins.io ephemeral agents to fix the following Windows builds error:
```
10:22:17  FAILURE: Build failed with an exception.
10:22:17  
10:22:17  * What went wrong:
10:22:17  Execution failed for task ':clean'.
10:22:17  > java.io.IOException: Unable to delete directory 'C:\Jenkins\agent\workspace\ugins_idea-stapler-plugin_PR-160\build'
10:22:17      Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
10:22:17      - C:\Jenkins\agent\workspace\ugins_idea-stapler-plugin_PR-160\build\tmp\.cache\expanded\expanded.lock
10:22:17      - C:\Jenkins\agent\workspace\ugins_idea-stapler-plugin_PR-160\build\tmp\.cache\expanded
10:22:17      - …
```
> fix(build): remove `clean` task to pass on Windows

- build.gradle
- src/main/java/org/kohsuke/stapler/idea/GotoViewAction.java
- src/main/java/org/kohsuke/stapler/idea/JellyTagLibReferenceProvider.java
- src/main/java/org/kohsuke/stapler/idea/JexlInspection.java
According to https://plugins.jetbrains.com/docs/intellij/api-changes-list-2023.html#8c50ccb_40 commons-lang2 and commons-collections libraries are being removed. Usages are replaced with IntelliJ and commons-text alternatives.
Fixes #167 
```[tasklist]
```
> Usages of Apache commons-lang2 are removed for IntelliJ compatibility reasons

- .run/idea-stapler-plugin [runIde 2023].run.xml
- .run/idea-stapler-plugin [runIde IU].run.xml
- Jenkinsfile
- build.gradle
- gradle.properties
Implements #174. Just like last year, bump the minimum required version by one year, which corresponds to 2022.3. 2022.2 onward requires Java 17, hence, Java is updated as well. There were a few releases of the JetBrains Gradle plugin since I last touched this, so it was updated as well. Persistent run configs are updated to enable testing on 2023 (one year more than the baseline).
```[tasklist]
```
> Update IntelliJ baseline to 2022

- src/main/java/io/jenkins/stapler/idea/jelly/DeprecatedStaplerJellyCustomTagAttributeInspection.java
- src/main/java/org/kohsuke/stapler/idea/dom/model/AttributeTag.java
- src/main/resources/META-INF/plugin.xml
- src/main/resources/inspectionDescriptions/DeprecatedStaplerJellyCustomTagAttribute.html
- src/test/java/io/jenkins/stapler/idea/jelly/DeprecatedStaplerJellyCustomTagAttributeInspectionTest.java
- src/test/testData/deprecateTagAttribute.jelly
- src/test/testData/testlib/test.jellytag
Fixes #172 by adding inspection for deprecated tags.
An inspection checks if the attribute of the custom tag is documented as deprecated and annotates it appropriately: "Attribute is deprecated. Use \"Go to declaration\" to find the recommended solution."
Created a Hello World plugin and used deprecated `title` attribute of `l:icon`:
```[tasklist]
```
> Report custom tag attributes that are marked deprecated.

- build.gradle
- src/main/java/io/jenkins/stapler/idea/jelly/IconSrcCompletionContributor.java
- src/main/java/io/jenkins/stapler/idea/jelly/InvalidIconSrcInspection.java
- src/test/java/io/jenkins/stapler/idea/jelly/IconSrcCompletionContributorTest.java
- src/test/java/io/jenkins/stapler/idea/jelly/InvalidIconSrcTest.java
Previously _only_ the `<l:icon />` component supports autocompletion for Symbols, this PR updates fixes that so that components with `icon` attributes now support autocompletion too.
* Still works for `src` attribute on `<l:icon />`
* Works for `icon` attributes
* Added additional tests
> Suggest symbols in "icon" attributes
